import type { Dictionary } from './kr';
export const en: Dictionary = {
 nav:['About IPIB','Education','Certification','Global','News','Contact'],skip:'Skip to content',menu:'Menu',close:'Close menu',language:'Select language',contact:'Contact us',
 heroTitle:['Individual potential.','Professional purpose.'],heroText:'From personal color to total image branding. Build your perspective through education, certification and global exchange.',educationCta:'Explore education',certificateCta:'Explore certification',visualLabel:'Color meets image',visualNote:'A color study of IPIB’s professional fields',
 aboutTitle:"Training Total Image Professionals",aboutText:'Based in Korea, IPIB connects personal color, fashion, beauty and image branding through professional education. Our approach starts with understanding individuality and developing that understanding into professional skills.',aboutLink:'Discover IPIB',pillars:['Education that builds expertise','Certification that connects learning','Exchange that broadens perspectives'],
 fieldsTitle:'Expertise through connection',fieldsText:'From understanding color to shaping an image strategy, five complementary disciplines form one Total Image education system.',fieldNames:['Personal Color','Fashion & Body Fit','Makeup & Hair','Beauty Image','Total Image Branding'],fieldDescriptions:['Start with color and the characteristics of the individual.','Connect body proportions, silhouettes and materials.','Explore color and form through makeup and hair.','Bring beauty elements together in a coherent image.','Shape an integrated strategy around individual identity and purpose.'],fieldCta:'Ask about this field',
 educationTitle:'From understanding\nto professional practice.',educationText:"From foundational and advanced study in a chosen field to total image expertise, IPIB educator certification and the Master / Certified Examiner course.",stages:['Understand','Analyze & practice','Apply in consulting'],stageTexts:['Explore body proportions, face shapes, skeletal structure and image.','Connect analysis with practical work on styling and materials.','Bring learning together through image analysis, feedback and consulting practice.'],curriculum:'View the published curriculum',educationNote:'Contact IPIB for course-specific schedules, curricula and entry requirements.',
 certificationTitle:'Your next step\nin professional learning.',certificationText:"From foundational and advanced study in a chosen field to total image expertise, IPIB educator certification and the Master / Certified Examiner course.",courseName:'Personal Color Bodyfit Consultant',courseLevel:'Published course · Level 1',certRows:['Courses & levels','Theory & practical curriculum','Assessment & qualification enquiries'],certNote:'Please confirm current availability, assessment eligibility and issuance requirements with IPIB.',courseLink:'View the published course',
 globalTitle:'Rooted in Korea.\nOpen to new perspectives.',globalText:'Connecting educators and professionals through education and image branding. Explore published collaboration records and course information for international learners.',globalLinks:['MOU & collaboration archive','International course enquiries','Partnership enquiries'],networkCaption:'A conceptual connection between education, expertise and international exchange',
 activitiesTitle:'Expertise, shaped together',activitiesText:'International exchange documented on IPIB’s official website.',activityNames:['IPIB × HAN Beauty, Hong Kong','Where education meets exchange'],activityCategories:['MOU ARCHIVE','GLOBAL EXCHANGE'],activityLink:'Explore the collaboration',
 leadershipTitle:'People at the heart\nof education.',leadershipText:'IPIB is represented by Manhee Kim. Understanding each individual’s unique image informs our approach to professional education.',leadershipLink:'About IPIB and its representative',leaderName:'Manhee Kim',leaderRole:'IPIB Representative',leaderNote:'A detailed biography will follow verified official materials.',portraitPlaceholder:'Official portrait coming soon',
 partnershipTitle:['A new connection.','A shared beginning.'].join('\n'),partnershipText:'For institutions and professionals exploring educational collaboration and professional exchange.',partnershipCta:'Discuss a partnership',
 newsTitle:'News & perspectives',newsText:'Find education updates and association activities through our official channels.',newsItems:['Official blog · Education & association news','Global exchange · MOU archive','Qualification courses · Curriculum'],newsCategories:['OFFICIAL CHANNEL','GLOBAL ACTIVITIES','EDUCATION UPDATE'],
 contactTitle:'What would you like to explore?',contactText:'Connect with our official channels for education, qualification courses and institutional partnerships.',contactTypes:['Education enquiries','Certification enquiries','Institutional partnerships'],emailCta:'Enquire by email',kakaoCta:'Kakao Channel',legalName:'International Personal Color Image Branding Association Inc.',representative:'Representative: Manhee Kim',registration:'Business registration: 810-87-03370',address:'Room 202, 2F, Daesin Building, 120-3 Cheongdam-dong, Gangnam-gu, Seoul, Korea',originalSite:'Original official website',privacy:'Privacy information',privacyText:'This preview does not collect or store enquiry data. Email and external channels are governed by the privacy policies of their respective services.',photoPlaceholder:'Education photography coming soon',photoSub:'Reserved for an authentic IPIB education photograph',more:'Learn more',external:'Visit the original official page',rights:'All rights reserved.'
};
