export const kr = {
  nav: ['협회 소개','교육','자격 인증','글로벌','소식','문의'],
  skip:'본문 바로가기', menu:'메뉴', close:'메뉴 닫기', language:'언어 선택', contact:'문의하기',
  heroTitle:['개인의 가능성을','전문가의 가치로'],
  heroText:'컬러에서 토탈 이미지 브랜딩까지. 교육과 자격 인증, 국제교류를 통해 전문가의 성장을 지원합니다.',
  educationCta:'교육 시스템 알아보기', certificateCta:'자격 인증 알아보기',
  visualLabel:'컬러와 이미지의 연결', visualNote:'IPIB 전문 분야를 표현한 컬러 스터디',
  aboutTitle:"토탈 이미지 전문가 양성기관",
  aboutText:'IPIB는 한국을 기반으로 퍼스널컬러, 패션, 뷰티와 이미지 브랜딩을 연결하는 전문 교육기관입니다. 개개인의 고유한 특성을 이해하고, 그 이해를 전문적인 역량으로 발전시키는 교육을 지향합니다.',
  aboutLink:'IPIB 소개 보기', pillars:['전문성을 키우는 교육','배움을 연결하는 자격','경계를 넓히는 교류'],
  fieldsTitle:'IPIB의 전문 교육 분야', fieldsText:'퍼스널컬러부터 패션, 메이크업과 헤어, 뷰티 이미지, 토탈 이미지 브랜딩까지 체계적으로 배웁니다.',
  fieldNames:['퍼스널컬러','패션 & 바디핏','메이크업 & 헤어','뷰티 이미지','토탈 이미지 브랜딩'],
  fieldDescriptions:['색의 특성과 개인에게 어울리는 컬러를 분석합니다.','체형과 실루엣, 소재를 고려한 패션 스타일링을 배웁니다.','얼굴의 특징과 컬러에 맞는 메이크업과 헤어 스타일을 배웁니다.','다양한 뷰티 요소를 활용해 조화로운 이미지를 완성합니다.','개인의 특성과 목적에 맞는 토탈 이미지 전략을 수립합니다.'],
  fieldCta:'이 분야 교육 문의',
  educationTitle:'전문 교육', educationText:"분야별 기초와 심화 교육에서 토탈 이미지 전문가, IPIB 인증 강사와 마스터·인증심사위원 과정으로 이어집니다.",
  stages:['이론과 이해','분석과 실습','컨설팅 적용'], stageTexts:['체형과 얼굴형, 골격 구조와 이미지의 관계를 이해합니다.','특성 분석과 진단, 패션 스타일·소재를 실습으로 연결합니다.','이미지 분석과 피드백, 컨설팅 실전 연습으로 배움을 정리합니다.'],
  curriculum:'기존 교육과정 살펴보기', educationNote:'과정별 커리큘럼·일정·수강 조건은 상담을 통해 확인해 주세요.',
  certificationTitle:'교육 단계와 자격 인증', certificationText:"분야별 기초와 심화 교육에서 토탈 이미지 전문가, IPIB 인증 강사와 마스터·인증심사위원 과정으로 이어집니다.",
  courseName:'퍼스널컬러바디핏 컨설턴트', courseLevel:'기존 홈페이지 공개 과정 · 1급',
  certRows:['자격과정 및 Level 안내','이론·실습 커리큘럼','평가 및 자격 취득 문의'],
  certNote:'과정의 최신 운영 여부와 응시·발급 조건은 협회에 문의해 주세요.', courseLink:'공개 자격과정 확인',
  globalTitle:'한국에서 시작해\n더 넓은 관점으로', globalText:'교육과 이미지 브랜딩을 매개로 국내외 교육기관과 전문가의 교류를 이어갑니다. 공개된 협력 기록과 해외 수강생을 위한 과정 안내를 만나보세요.',
  globalLinks:['MOU · 협력 기록','해외 수강생 과정 문의','파트너십 문의'], networkCaption:'교육 · 전문성 · 국제교류를 연결하는 개념도',
  activitiesTitle:'IPIB 교육과 교류 활동', activitiesText:'IPIB 공식 홈페이지에 공개된 국제교류의 기록.', activityNames:['IPIB × HAN Beauty, Hong Kong','교육과 교류가 만나는 자리'], activityCategories:['MOU ARCHIVE','GLOBAL EXCHANGE'], activityLink:'협력 기록 보기',
  leadershipTitle:'교육의 중심에는\n사람이 있습니다', leadershipText:'IPIB 대표 김만희. 개인의 고유한 이미지를 이해하는 시선에서 전문 교육의 방향을 찾아갑니다.', leadershipLink:'협회 소개와 대표 정보', leaderName:'김만희', leaderRole:'IPIB 대표', leaderNote:'상세 약력은 공식 자료 확인 후 제공됩니다.', portraitPlaceholder:'대표 프로필 사진 준비 중',
  partnershipTitle:'교육 협력', partnershipText:'국내외 교육기관 및 전문가와 교육 협력 방안을 논의합니다.', partnershipCta:'파트너십 문의하기',
  newsTitle:'IPIB 소식', newsText:'IPIB의 교육 현장과 협회 활동, 국내외 교류 소식을 전합니다.', newsItems:['공식 블로그 · 교육 및 협회 소식','글로벌 교류 · MOU 아카이브','자격과정 · 커리큘럼 안내'], newsCategories:['OFFICIAL CHANNEL','GLOBAL ACTIVITIES','EDUCATION UPDATE'],
  contactTitle:'교육과 자격 과정이 궁금하신가요?', contactText:'교육, 자격과정, 기관 협력에 관한 문의를 공식 채널로 연결합니다.', contactTypes:['교육 문의','자격 인증 문의','기관 및 파트너십 문의'], emailCta:'이메일로 문의', kakaoCta:'카카오 채널',
  legalName:'주식회사 국제퍼스널컬러이미지브랜딩협회', representative:'대표 김만희', registration:'사업자등록번호 810-87-03370', address:'서울특별시 강남구 청담동 120-3 대신빌딩 2층 202호',
  originalSite:'기존 공식 홈페이지', privacy:'개인정보 안내', privacyText:'IPIB 공식 홈페이지는 문의 내용을 직접 수집하거나 저장하지 않습니다. 이메일 및 외부 채널 이용 시 해당 서비스의 개인정보 처리방침이 적용됩니다.', photoPlaceholder:'실제 교육 사진 준비 중', photoSub:'IPIB 교육 현장 이미지로 교체 예정',
  more:'자세히 보기', external:'기존 공식 페이지로 이동', rights:'All rights reserved.',
};
export type Dictionary = typeof kr;
