export const slugs=['personal-color','fashion-body-fit','makeup-hair','beauty-image','total-image-branding'];
export const sections=['about','education','certification','global','news','contact'];
export const nav=['ABOUT','EDUCATION','CERTIFICATION','GLOBAL NETWORK','NEWS','CONTACT'];
export const extra={
 kr:{hero:'이미지 전문가의\n시작과 완성\n국제퍼스널컬러이미지브랜딩협회',intro:'검증된 교육 프로그램과 전문 자격 시스템으로\n글로벌 이미지 브랜딩 시장을 이끌어갑니다.',discover:'살펴보기',pending:'공식 자료 확인 후 업데이트 예정입니다.',vision:'개인의 고유함을 이해하는 교육',visionText:'컬러, 형태, 스타일을 함께 바라봅니다. 다섯 전문 분야를 연결해 개인의 특성과 목적에 맞는 이미지 브랜딩을 탐구합니다.',history:'연혁',organization:'조직',president:'김만희',roles:['IPIB 협회장','STYLEMAHN 대표','건국대학교 외래교수','30여 년 경력의 퍼스널 이미지 컨설팅 전문가'],profile:'협회장 소개',general:'일반 문의',choose:'문의 목적을 선택해 주세요',email:'이메일 작성하기',mailNote:'선택한 주제로 이메일 앱이 열립니다. 이 사이트는 문의 내용을 수집하거나 저장하지 않습니다.',archive:'공식 홈페이지 공개 기록',all:'전체',empty:'등록된 게시물이 없습니다.',categories:['협회 소식','교육','세미나','글로벌 활동','공지사항'],level:'Level별 과정',process:'자격 취득 절차',qualification:'자격 정보',notice:'과정 안내',confirm:'운영 일정, 응시 조건, 평가 방식과 발급 기준은 협회의 최신 안내를 확인해 주세요.',network:'교육을 통한 국제교류',mou:'IPIB × HAN Beauty 홍콩 MOU',mouText:'기존 공식 홈페이지에 공개된 HAN Beauty 홍콩과의 MOU 및 교류 기록입니다.',source:'공식 자료 보기',inquiry:'과정 및 상담 안내',related:'관련 교육 분야',back:'목록으로',privacy:'개인정보 안내'},
 en:{hero:'Image expertise.\nConnected.',intro:'An image branding institution connecting education, certification and a global network.',discover:'Discover',pending:'To be updated following confirmation of official information.',vision:'Education that understands individuality',visionText:'We consider colour, form and style together. Five connected disciplines explore image branding through individual characteristics and goals.',history:'History',organization:'Organization',president:'Manhee Kim',roles:['President of IPIB','CEO of STYLEMAHN','Adjunct lecturer, Konkuk University','Personal image consulting expert with around 30 years of experience'],profile:'Expertise that shapes education',general:'General Inquiry',choose:'Select your inquiry',email:'Compose an email',mailNote:'Your email app opens with the selected subject. This website does not collect or store inquiry information.',archive:'Official website archive',all:'All',empty:'No published articles in this category.',categories:['IPIB News','Education','Seminar','Global Activities','Notice'],level:'Level structure',process:'Certification process',qualification:'Qualification information',notice:'Course guidance',confirm:'Please contact IPIB for current schedules, eligibility, assessment and issuance requirements.',network:'International exchange through education',mou:'IPIB × HAN Beauty Hong Kong MOU',mouText:'A record of the MOU and exchange with HAN Beauty Hong Kong, published on the existing official website.',source:'View official source',inquiry:'Course information & inquiries',related:'Connected disciplines',back:'Back to articles',privacy:'Privacy information'},
 cn:{hero:'理解个人形象，\n连接专业价值。',intro:'连接专业教育、资格认证与全球网络的形象品牌专业机构。',discover:'了解更多',pending:'待官方资料确认后更新。',vision:'理解个体独特性的教育',visionText:'将色彩、形态与风格相结合，通过五个相互关联的专业领域，探索符合个人特质与目标的形象品牌。',history:'发展历程',organization:'组织架构',president:'Manhee Kim (김만희)',roles:['IPIB 协会会长','STYLEMAHN 代表','建国大学外聘讲师','拥有约30年经验的个人形象咨询专家'],profile:'以专业经验引领教育',general:'一般咨询',choose:'请选择咨询主题',email:'撰写电子邮件',mailNote:'将打开电子邮件应用并填写所选主题。本网站不收集或保存咨询内容。',archive:'官方网站公开档案',all:'全部',empty:'此分类暂无文章。',categories:['协会新闻','教育','研讨会','全球活动','公告'],level:'等级课程',process:'资格取得流程',qualification:'资格信息',notice:'课程说明',confirm:'最新课程安排、报名条件、考核及证书颁发要求，请向协会咨询。',network:'以教育连接国际交流',mou:'IPIB × 香港 HAN Beauty 合作备忘录',mouText:'现有官方网站公开的与香港 HAN Beauty 签署合作备忘录及交流活动记录。',source:'查看官方资料',inquiry:'课程介绍与咨询',related:'相关专业领域',back:'返回文章列表',privacy:'隐私说明'},
 jp:{hero:'イメージを理解し、\n専門性をつなぐ。',intro:'専門教育、資格認証、グローバルネットワークをつなぐイメージブランディング専門機関。',discover:'詳しく見る',pending:'公式資料の確認後に更新予定です。',vision:'一人ひとりの個性を理解する教育',visionText:'色彩、形、スタイルを総合的に捉えます。五つの専門分野をつなぎ、個人の特性と目的に合うイメージブランディングを探究します。',history:'沿革',organization:'組織',president:'キム・マンヒ',roles:['IPIB 会長','STYLEMAHN 代表','建国大学 非常勤講師','約30年の経験を持つパーソナルイメージコンサルティング専門家'],profile:'専門性が導く教育',general:'一般のお問い合わせ',choose:'お問い合わせ内容を選択してください',email:'メールを作成',mailNote:'選択した件名でメールアプリが開きます。このサイトではお問い合わせ内容を収集・保存しません。',archive:'公式サイト公開アーカイブ',all:'すべて',empty:'このカテゴリーの記事はまだありません。',categories:['協会ニュース','教育','セミナー','グローバル活動','お知らせ'],level:'レベル別コース',process:'資格取得の流れ',qualification:'資格情報',notice:'コースのご案内',confirm:'最新の日程、受講条件、評価方法、発行要件は協会にお問い合わせください。',network:'教育でつながる国際交流',mou:'IPIB × 香港 HAN Beauty MOU',mouText:'既存の公式サイトで公開された、香港 HAN BeautyとのMOUと交流の記録です。',source:'公式資料を見る',inquiry:'コースのご案内・お問い合わせ',related:'つながる専門分野',back:'記事一覧へ',privacy:'個人情報について'}
};


