export const training = {
  "kr": {
    "lecture": "전문 교육 현장",
    "practice": "분석과 실습",
    "title": "교육 현장",
    "text": "강의, 교구 분석, 진단 시연과 실습으로 이어지는 IPIB 교육 현장입니다.",
    "leadership": "교육 활동",
    "authority": "김만희 회장의 30여 년 이미지 컨설팅 경험을 바탕으로, 컬러·스타일·뷰티의 이론과 실무를 연결합니다.",
    "reference": "교육 자료와 연구",
    "video": "진단 시연 영상",
    "photos": [
      "강의와 교육 자료",
      "진단 과정 실습",
      "분석과 설명",
      "컬러 드레이핑 실습",
      "교육 현장 강의",
      "강의와 질의응답",
      "개별 설명과 피드백",
      "사례 중심 교육",
      "실습 과정 기록",
      "교구를 활용한 설명",
      "관찰과 진단 실습",
      "소그룹 실습"
    ],
    "globalTitle": "IPIB 해외지부 및 교육 협력",
    "globalText": "IPIB의 교육 시스템을 바탕으로 해외 교육기관 및 전문가와의 협력을 논의합니다. 해외지부·공식 교육기관 자격은 별도 심사와 본부 승인을 통해 부여됩니다.",
    "globalCta": "해외지부·교육 협력 문의"
  },
  "en": {
    "lecture": "Professional education in practice",
    "practice": "Analysis & practice",
    "title": "From theory to professional practice.",
    "text": "IPIB education through lectures, teaching tools, diagnostic demonstrations and practice.",
    "leadership": "around 30 years of experience, shared through education",
    "authority": "President Manhee Kim connects theory and practice in color, style and beauty through around 30 years of image consulting experience.",
    "reference": "Teaching resources & study",
    "video": "Diagnostic demonstration",
    "photos": [
      "Lecture and teaching materials",
      "Diagnostic practice",
      "Analysis and explanation",
      "Color draping practice",
      "Classroom teaching",
      "Lecture and discussion",
      "Individual explanation and feedback",
      "Case-based learning",
      "Practice in progress",
      "Explaining with teaching tools",
      "Observation and diagnostic practice",
      "Small-group practice"
    ],
    "globalTitle": "IPIB Overseas Branches & Education Partnerships",
    "globalText": "Explore educational cooperation with IPIB. Overseas branch and official education institution status require separate review and headquarters approval.",
    "globalCta": "Discuss a branch or education partnership"
  },
  "cn": {
    "lecture": "专业教学现场",
    "practice": "分析与实操",
    "title": "学习理论，应用于实践。",
    "text": "通过讲授、教具分析、诊断示范与实操，了解 IPIB 的教学现场。",
    "leadership": "将约30年实务经验融入教育",
    "authority": "以会长 Manhee Kim 的约30年形象咨询经验为基础，连接色彩、风格与美容领域的理论和实践。",
    "reference": "教学资料与研究",
    "video": "诊断示范视频",
    "photos": [
      "授课与教学资料",
      "诊断实操",
      "分析与讲解",
      "色彩布诊断实操",
      "课堂教学",
      "授课与交流",
      "个别讲解与反馈",
      "案例教学",
      "实操记录",
      "教具讲解",
      "观察与诊断实操",
      "小组实操"
    ],
    "globalTitle": "IPIB 海外分会与教育合作",
    "globalText": "欢迎海外教育机构与专业人士洽谈 IPIB 教育合作。海外分会及官方教育机构资格须经独立审核并获总部批准。",
    "globalCta": "咨询海外分会与教育合作"
  },
  "jp": {
    "lecture": "専門教育の現場",
    "practice": "分析と実習",
    "title": "理論を学び、実践につなげる。",
    "text": "講義、教材の分析、診断デモンストレーションと実習。IPIBの教育現場をご紹介します。",
    "leadership": "約30年の現場経験を教育へ",
    "authority": "キム・マンヒ会長の約30年にわたるイメージコンサルティング経験をもとに、カラー・スタイル・ビューティーの理論と実践をつなぎます。",
    "reference": "教育資料と研究",
    "video": "診断デモンストレーション",
    "photos": [
      "講義と教育資料",
      "診断実習",
      "分析と説明",
      "カラードレーピング実習",
      "教育現場の講義",
      "講義と対話",
      "個別の説明とフィードバック",
      "事例を通じた学習",
      "実習の記録",
      "教材を用いた説明",
      "観察と診断実習",
      "少人数での実習"
    ],
    "globalTitle": "IPIB 海外支部・教育連携",
    "globalText": "IPIBの教育システムを通じた海外教育機関・専門家との連携をご相談いただけます。海外支部・公式教育機関の資格には、別途審査と本部承認が必要です。",
    "globalCta": "海外支部・教育連携について相談"
  }
};
