import type {Locale} from '@/content/site';
const copy={
 kr:{title:'브랜드 아이덴티티',intro:'IPIB의 브랜드 컬러는 마젠타, 스카이 블루, 화이트입니다.',outro:'IPIB는 교육과 자격 인증을 통해 각자의 개성과 전문성을 갖춘 전문가의 성장을 지원합니다.',items:[['마젠타','창조성 · 개성 · 혁신','새로운 길을 열고, 독창적인 전문가로 성장하는 에너지를 담습니다. 교육과 자격 과정을 통해 자신만의 관점과 개성을 발견하고 창의적으로 표현합니다.'],['스카이 블루','신뢰 · 지혜 · 가능성','전문가로서 쌓아가는 신뢰와 지혜, 그리고 열린 가능성을 상징합니다. 배움으로 다진 전문성을 바탕으로 자신의 역량을 세상에 펼쳐갑니다.'],['화이트','순수함 · 투명성 · 자신감','모든 색을 담는 순수함과 투명성을 상징합니다. 각자가 지닌 고유한 아름다움을 선명하게 드러내고, 자신을 더욱 자신 있게 표현할 수 있는 가능성을 담습니다.']]},
 en:{title:'The colors of IPIB. The possibility to grow.',intro:'IPIB’s brand identity is built on three colors: magenta, sky blue and white.',outro:'Through education and certification, IPIB supports the growth of trusted professionals who express their unique colors and individuality in harmony.',items:[['Magenta','Creativity · Individuality · Innovation','The energy to open new paths and grow into an original, creative professional. Through education and certification, individuals discover their own perspective and express it with creativity.'],['Sky Blue','Trust · Wisdom · Possibility','Trust, wisdom and open possibilities developed through professional learning. It represents the confidence to bring expertise and new potential to the world.'],['White','Purity · Transparency · Confidence','A foundation that holds every color. White reveals each person’s unique beauty with clarity and creates room for confident self-expression.']]},
 cn:{title:'IPIB的色彩，专业成长的可能',intro:'IPIB的品牌形象以洋红、天蓝和白色三种色彩为基础。',outro:'IPIB通过教育与资格课程，支持学员成长为值得信赖的专业人士，并和谐地展现自己的色彩与个性。',items:[['洋红','创造力 · 个性 · 创新','象征开拓新道路、成长为独具创意的专业人士的能量。通过教育与资格课程，发现个人视角与个性，并以创意表达自我。'],['天蓝','信赖 · 智慧 · 可能性','象征专业学习中积累的信赖与智慧，以及开放的可能。以学习建立的专业能力为基础，向世界展现自己的实力。'],['白色','纯净 · 透明 · 自信','象征包容所有色彩的纯净与透明。清晰呈现每个人独特的美，让自我表达更加自信。']]},
 jp:{title:'IPIBの色、専門家として育つ可能性',intro:'IPIBのブランドアイデンティティは、マゼンタ・スカイブルー・ホワイトの3色を基盤としています。',outro:'IPIBは教育と資格課程を通じて、信頼される専門家への成長を支え、自分らしい色と個性を調和させて表現する土台を築きます。',items:[['マゼンタ','創造性 · 個性 · 革新','新しい道を開き、独創的な専門家へと成長するエネルギーを表します。教育と資格課程を通じて、自分らしい視点と個性を見つけ、創造的に表現します。'],['スカイブルー','信頼 · 知恵 · 可能性','専門家として培う信頼と知恵、そして開かれた可能性を象徴します。学びによって築いた専門性をもとに、自らの力を社会に発信します。'],['ホワイト','純粋さ · 透明性 · 自信','すべての色を受け止める純粋さと透明性を象徴します。一人ひとりの美しさを鮮明に映し出し、自信を持って表現する可能性を込めています。']]}
};
const colors=[{name:'MAGENTA',hex:'#FF26AB'},{name:'SKY BLUE',hex:'#008BCF'},{name:'WHITE',hex:'#FFFFFF'}];
export function BrandColors({locale}:{locale:Locale}){const t=copy[locale];return <section className="brand-colors wrap" aria-labelledby="brand-colors-title"><header className="brand-color-heading"><p className="eyebrow">IPIB BRAND IDENTITY</p><h2 id="brand-colors-title">{t.title}</h2><p className="lead">{t.intro}</p></header><div className="brand-color-grid">{t.items.map(([name,meaning,text],i)=><article key={name}><div className={`brand-swatch brand-swatch-${i}`}><div className="brand-swatch-label"><strong>{colors[i].name}</strong><span>{colors[i].hex}</span></div></div><div className="brand-color-copy"><h3>{name}</h3><p className="brand-color-meaning">{meaning}</p><p>{text}</p></div></article>)}</div><p className="brand-color-outro">{t.outro}</p></section>}
