import {BrandText} from './BrandText';
import {BranchDirectory} from './BranchDirectory';
import {fieldDetails} from '@/content/field-details';
import {ProfileHighlights} from './ProfileHighlights';
import {LeadershipCredentials} from './LeadershipCredentials';
import {BrandColors} from './BrandColors';
import {NewsGallery} from './NewsGallery';
import {TrainingGallery,TeachingProfile,GlobalEducationGallery} from './TrainingGallery';
import {training} from '@/content/training';
import {EducationSystem} from './EducationSystem';
import {editorial} from '@/content/editorial';
import {ArrowUpRight,EnvelopeSimple,ChatCircle} from '@phosphor-icons/react/dist/ssr';
import Link from './PageLink';
import {getDictionary} from '@/content';
import {extra,slugs,sections} from '@/content/redesign';
import {archives} from '@/content/archives';
import {fields,source,type Locale} from '@/content/site';
import {Photo,More,Partnership} from './Site';
import type {PageEdit,NewsEdit} from '@/lib/cms';
import {ContactOptions,NewsList} from './Interactive';
function PageHeading({locale,label,title,text,edit}:{locale:Locale;label:string;title:string;text:string;edit?:PageEdit|null}){return <div className="page-heading wrap"><p className="eyebrow">{label}</p><h1><BrandText text={label==='IPIB NEWS'||label==='GLOBAL ACTIVITIES / ARCHIVE'?(edit?.title||title):(edit?.title||title).replace(/[,.]/g,'')}/></h1><p className="lead"><BrandText text={edit?.description||text}/></p>{(label==='EDUCATION'||label==='CERTIFICATION')&&<div className="page-inquiry"><div><strong>{{kr:'교육·자격·협력 문의',en:'Education, certification & partnerships',cn:'教育·资格·合作咨询',jp:'教育・資格・連携のお問い合わせ'}[locale]}</strong><span>{{kr:'궁금한 내용을 문의해 주세요.',en:'Get in touch with your questions.',cn:'欢迎联系我们。',jp:'ご不明な点はお気軽にご相談ください。'}[locale]}</span></div><a className="inquiry-primary" href={`/${locale}/contact`}><EnvelopeSimple size={21} aria-hidden="true"/>{{kr:'문의하기',en:'Contact us',cn:'联系我们',jp:'お問い合わせ'}[locale]}</a><a className="inquiry-secondary" href={source.kakao} target="_blank" rel="noopener noreferrer"><ChatCircle size={21} weight="fill" aria-hidden="true"/>{{kr:'카카오톡 문의',en:'KakaoTalk',cn:'KakaoTalk咨询',jp:'KakaoTalk'}[locale]}</a></div>}{edit?.image&&<img className="cms-page-image" src={edit.image} alt={edit.title}/>}</div>}
export function DetailPage({locale,slug,edit,news}:{locale:Locale;slug:string;edit:PageEdit|null;news:NewsEdit[]}){const d=getDictionary(locale),t=extra[locale],e=editorial[locale],v=training[locale];const field=slugs.indexOf(slug.split('/')[1]);const entry=news.find(a=>slug==='news/'+a.slug);return <main id="main" className={`detail-page page-${slug.split("/")[0]}`}><div className="wrap breadcrumbs"><Link href={`/${locale}`}>{e.home}</Link><span aria-hidden="true">/</span><span>{slug.startsWith("education/")?fields[field]:slug.startsWith("news/")?d.nav[4]:d.nav[sections.indexOf(slug)]}</span></div>
{slug==='about'&&<><PageHeading locale={locale} edit={edit} label="ABOUT IPIB" title={d.aboutTitle.replace('\n',' ')} text={d.aboutText}/><section id="leadership" className="wrap leadership"><div className="section-heading"><p className="eyebrow">PRESIDENT / LEADERSHIP</p><h2>{t.profile}</h2></div><div className="portrait-layout"><div className="profile-visuals"><Photo name="president-kim-manhee-01.png" alt={t.president+' — '+t.roles[0]}/><Photo name="ipib-training-03.jpg" alt={t.president+" — "+v.lecture} className="profile-lecture"/></div><div className="profile-copy"><ProfileHighlights locale={locale} name={t.president}/><LeadershipCredentials locale={locale}/></div></div></section><TeachingProfile locale={locale}/><BrandColors locale={locale}/></>}
{slug==='education'&&<><PageHeading locale={locale} edit={edit} label="EDUCATION" title={d.educationTitle.replace('\n',' ')} text={d.fieldsText}/><section className="wrap course-directory"><div className="section-heading"><p className="eyebrow">PROFESSIONAL FIELDS</p><h2>{e.disciplines}</h2></div>{fields.map((f,i)=><Link href={`/${locale}/education/${slugs[i]}`} key={f}><span className="eyebrow">0{i+1}</span><h2>{f}</h2><p>{d.fieldDescriptions[i]}</p><span className="text-link">{t.discover} <ArrowUpRight size={18} aria-hidden="true"/></span></Link>)}</section><TrainingGallery locale={locale}/><Partnership locale={locale}/></>}
{slug.startsWith('education/')&&field>=0&&<><PageHeading locale={locale} edit={edit} label="EDUCATION" title={fields[field]} text={d.fieldDescriptions[field]}/><section className="wrap field-detail"><div><h2>{d.fieldNames[field]}</h2><p className="lead">{fieldDetails[locale][field]}</p><h3>{t.inquiry}</h3><p>{d.educationNote}</p><p className="pending">{t.pending}</p><More locale={locale} to="contact">{d.fieldCta}</More></div><Photo eager className={`field-photo field-photo-${field}`} name={["education-personal-color.webp","education-body-fit.webp","education-makeup-hair.webp","education-beauty-image.webp","education-total-image.webp"][field]} alt={d.fieldNames[field]}/></section><section className="wrap related"><h2>{t.related}</h2>{fields.map((f,i)=>i!==field&&<More key={f} locale={locale} to={`education/${slugs[i]}`}>{f}</More>)}</section></>}
{slug==='certification'&&<><PageHeading locale={locale} edit={edit} label="CERTIFICATION" title={d.certificationTitle.replace('\n',' ')} text={d.certificationText}/><EducationSystem locale={locale}/></>}
{slug==='global'&&<><PageHeading locale={locale} edit={edit} label="GLOBAL NETWORK" title={v.globalTitle} text={v.globalText}/><BranchDirectory locale={locale}/><div className="wrap network-record"><p className="eyebrow">MOU ARCHIVE</p><div><span>IPIB · Korea</span><span className="connection-rule" aria-hidden="true"></span><span><span className="brand-name-nowrap">HAN Beauty</span> · Hong Kong</span></div><p>{e.archive}</p></div>{archives.filter(record=>record.slug==='han-beauty-mou').map(record=><section className="wrap global-archive" key={record.slug}>{record.image&&<Photo eager name={record.image.replace("/assets/","")} alt={record.title[locale]}/>}<div className="archive-description"><p className="eyebrow">PARTNERS / MOU · {record.location}</p><h2><BrandText text={record.title[locale]}/></h2><p><BrandText text={record.description[locale]}/></p></div>{record.document&&<Photo name={record.document.replace("/assets/","")} alt={record.title[locale]}/>}</section>)}<GlobalEducationGallery locale={locale}/><div className="wrap international-link"><a className="text-link" href={`/${locale}/contact`}>{d.globalLinks[1]}<ArrowUpRight size={18} aria-hidden="true"/></a></div></>}
{slug==='news'&&<><PageHeading locale={locale} edit={edit} label="NEWS & INSIGHTS" title={d.newsTitle} text={d.newsText}/><section className="wrap news-list"><NewsList locale={locale} entries={news}/></section></>}
{entry&&<><PageHeading locale={locale} label={entry.slug==='han-beauty-mou'?'GLOBAL ACTIVITIES / ARCHIVE':'IPIB NEWS'} title={entry.title[locale]} text={entry.description[locale]}/><article className="wrap article">{entry.image&&<a className="article-cover-original" href={entry.image} target="_blank" rel="noopener noreferrer"><img className="cms-article-image" src={entry.image} alt={entry.title[locale]}/></a>} {entry.document&&<><p>{t.archive}</p><Photo name={entry.document.replace("/assets/","")} alt={entry.title[locale]}/></>}{entry.body?.[locale]&&<div className="article-body">{entry.body[locale].split("\n").filter(Boolean).map((paragraph,i)=><p key={i}><BrandText text={paragraph}/></p>)}</div>}{Boolean(entry.gallery?.length)&&<NewsGallery images={entry.gallery!} title={entry.title[locale]} locale={locale}/>} {entry.source&&<a className="text-link" href={entry.source}>{t.source} <ArrowUpRight size={18} aria-hidden="true"/></a>}<More locale={locale} to="news">{t.back}</More></article></>}
{slug==='contact'&&<><PageHeading locale={locale} edit={edit} label="CONTACT" title={e.contact} text={d.contactText}/><section className="wrap"><ContactOptions locale={locale}/><div className="contact-address"><h3>IPIB</h3><p>{d.address}</p><a href="mailto:stylemahn@naver.com">stylemahn@naver.com</a></div></section></>}
</main>}



